### ISSUE TITLE
chore: param store doesn't use gas kv

### ISSUE THREAD

**Issue by 0Tech** [Finschia/cosmos-sdk#23]

**Comment by ulbqb** [comment]
- PR - Finschia/finschia-sdk#202
- Type - Core
- Desc - 
  1. Remove unused functions
  2. Use non-gas KV Store in param because param doesn't use gas.
- Decision - Abandon
  - This change is related to x/param and it's deprecated.

Related PR
- PR - Finschia/finschia-sdk#198
- Type - Core
- Desc - Replace this mutex with RWMutex
- Decision - Abandon
  1. This change is related to x/param and it's deprecated.
